### ISSUE TITLE
the field of Deposit and Withdraw cell

### ISSUE THREAD

**Issue by Rbchi** [nervosnetwork/rfcs#143]
Why you call _`Nervos DAO deposit cell`_ and then add 'ing' on the `Nervos DAO withdrawing cell.`?

**Comment by janx** [comment]
Because the withdraw is a 2-step process, after the first withdraw transaction included the cell is in `withdrawing` status.

**Comment by Rbchi** [comment]
Thanks for replying！
As NervosDao Rfc mentioned:

```
The Nervos DAO interest is calculated with the following formula:
( c_t - c_o ) * AR_n / AR_m - ( c_t - c_o )
```

Is the reason c_o existing that the contract in NervosDao also need some capacitied to record ?

```
Meaning` that the maximum total withdraw capacity one can get from this Nervos DAO input cell is:

( c_t - c_o ) * AR_n / AR_m + c_o
```

Does it mean when the value of  c_t  is 0? However,at that time,  ( c_t - c_o )  would be negative.

**Comment by janx** [comment]
For example, for a deposit cell whose capacity is 2000 CKBytes, and its `capacity`, `data`, `lock` and `type` used 120 CKBytes together, `c_t` is 2000 CKBytes, and `c_o` is 120 CKBytes, deposited capacity (principal) is 1880 CKBytes. Thus CKBytes in use (as data storage) are excluded from interest calculation, and you can either use CKBytes as storage or hold it in NervosDAO but not both.

The deposit cells always follow the same rule as any other cell: cell capacity must be larger than or equal to occupied capacity, which means `c_t - c_o` can never be negative.

**Comment by Rbchi** [comment]
Thank you very much, Janx
Very detailed explanation 
Does it mean the value of c_t is 0 when interest reaches the max like below?
```
  ( c_t - c_o ) * AR_n / AR_m + c_o
```

**Comment by doitian** [comment]
> Thank you very much, Janx
> Very detailed explanation
> Does it mean the value of c_t is 0 when interest reaches the max like below?
> 
> ```
>   ( c_t - c_o ) * AR_n / AR_m + c_o
> ```

I think you mean `c_o` is 0 when interest reaches the max? Yes, but `c_0` can never be 0.

**Comment by Rbchi** [comment]
Yes,that’s why I felt strange why the RFC mentioned:

The Nervos DAO interest is as following :
`( c_t - c_o ) * AR_n / AR_m - ( c_t - c_o )`

I don’t know why the maximum total withdraw is 
`( c_t - c_o ) * AR_n / AR_m + c_o`

**Comment by doitian** [comment]
Where `c_t` is your principle, `c_t + interest` is your total withdraw amount.
