### ISSUE TITLE
RFC-21 CKB Address Format need to be update

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/rfcs#152]
- [x] Add test vectors for `SECP256K1 + multisig`
- [x] Update test vectors for `Full Payload Format`
- [x] Update the picture which explain the Address Format #151 
- [x] IMHO, change `single_arg` to `args` will be better
- [ ] If use `multisig` together with `since` we should emphasize must use **Full Payload Format** instead. (From @TheWaWaR)

**Comment by TheWaWaR** [comment]
If use `multisig` together with `since` we should emphasize must use **Full Payload Format** instead.

**Comment by CipherWang** [comment]
> If use `multisig` together with `since` we should emphasize must use **Full Payload Format** instead.

The `since` infomation and it's usage should be provided by multisig script documents, this rfc is focus on format.

Other issues metioned here has been commited #151
