### ISSUE TITLE
What is the meaning of The number of units of computation (called “cycles”)?

### ISSUE THREAD

**Issue by Rbchi** [nervosnetwork/rfcs#157]
As mentioning in the RFC015,what is the meaning of The number of units of computation (called “cycles”)?Does It means how many resources that a tx's computation cycles would take？

**Comment by xxuejie** [comment]
One way to think of it, is a way to measure program running time that is decoupled from computer specs. If a program contains more logic and runs longer, it should consume more `cycles`, if a program does less and runs shorter, it should then consume less `cycles`. We are using this idea to model the complexity of scripts running in CKB. In a way, it is also similar to the gas concept in Ethereum.

**Comment by Rbchi** [comment]
Totally understand.T.Y
