### ISSUE TITLE
海绵函数的伪代码有些问题

### ISSUE THREAD

**Issue by Jackieyewang** [nervosnetwork/rfcs#177]

**Comment by Jackieyewang** [comment]
// absorb
    for chunk in chunks do:
        state[0:r] = state[0:r] xor chunk
        state = F(state)
这段的state[0:r] = state[0:r] xor chunk应该是state[0:r] = state[0:r] xor chunk || 0<sup>c</sup>

**Comment by quake** [comment]
@Jackieyewang 前面的伪代码有初始化state为0，所以这里不需要 `|| 0`
```
    // initialize state
    state = zeros(r+c)
```
