### ISSUE TITLE
hash_type为Data时，code_hash 对应script的代码，为Type时code_hash 对应type script，这里是不是重复了，Data是对应lock script？

### ISSUE THREAD

**Issue by Jackieyewang** [nervosnetwork/rfcs#179]

**Comment by doitian** [comment]
A cell has following fields:

- capacity
- data
- lock script
- type script

Data matches the cell on `Hash(cell.data)`. Type matches `Hash(cell.type_script)`

**Comment by Jackieyewang** [comment]
我指的是交易结构中，在cell的script里面的hash_type
