### ISSUE TITLE
where is the  (Figure 4). on rfc 002?

### ISSUE THREAD

**Issue by Rbchi** [nervosnetwork/rfcs#182]
like the title,where is the  (Figure 4). on RFC002?
And is deps cell necessary for a transaction?
Or is that only necessary when I need to index script from previous cell ?

**Comment by janx** [comment]
Should be "Figure 3".

In theory deps are not necessary if the verification of transaction doesn't rely on any previous script. In practice, most transactions refer to common scripts such as `secp256k1_blake160_sighash_all`.
