### ISSUE TITLE
About the governance operation of sUDT

### ISSUE THREAD

**Issue by Rbchi** [nervosnetwork/rfcs#208]
> Simple UDT Rule 5: in a governance operation, at least one input cell in the transaction should use owner lock specified by the SUDT as its cell lock.
Today,we could find that it may be not just two roles in a single smart contract, for example, there may be lots of different roles on a DeFi contract including owner, admin, pauser, user, etc..
How to deal with that if today a dev wants to create numerous kinds of users to interact on their sUDT script?

**Comment by driftluo** [comment]
The current lockscript on the chain are all with sole ownership, but this is not the only mode.


If you need multiple levels of privilege to give away, it means that you need a lock that supports different levels of operation, e.g. the owner can change the owner of the lock, the administrator can't change the owner of the lock, but can change the typescript or the data in the data filed, etc. This can be done via the lockscript definition
