### ISSUE TITLE
Refactor 0024 CKB System Script List

### ISSUE THREAD

**Issue by janx** [nervosnetwork/rfcs#300]
https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0024-ckb-system-script-list/0024-ckb-system-script-list.md

This RFC's scope is too large to maintain because it includes all possible future system scripts. The RFC is on the 'Informational' track which conflicts with its ever-growing nature, it can never be made 'final'.

Suggestions:
- Rename it to 'CKB Genesis Script List'. There're two benefits: 1. Genesis Script List has a fixed scope of scripts; 2. 'Genesis Script' is more clearly defined than 'System Script'. There's no formal definition of system script, and it seems people call every important script 'system script'.
- Scripts added later like 'Cheque' and 'sUDT' can be separated into their own RFC. Every important lock/type script deserves its own RFC with a detailed behavior description.

cc @duanyytop

**Comment by duanyytop** [comment]
OK. I see.
So the scripts that really meet 'CKB Genesis Script List' should be `SECP256K1/blake160`, `SECP256K1/multisig` and `Nervos DAO`, any ideas?

**Comment by janx** [comment]
Yes.

**Comment by duanyytop** [comment]
Maybe `Type Id` also belongs to 'CKB Genesis Script List', do you think so?

**Comment by janx** [comment]
> Maybe `Type Id` also belongs to 'CKB Genesis Script List', do you think so?

Yes.

**Comment by duanyytop** [comment]
https://github.com/nervosnetwork/rfcs/pull/301
