### ISSUE TITLE
Need a place to put the information of anyone_can_pay/cheque/sudt scripts

### ISSUE THREAD

**Issue by TheWaWaR** [nervosnetwork/rfcs#304]
Due to   PR #301 , anyone_can_pay/cheque/sudt script information are removed. Need a new place to put those information.

`sudt` deployment information can add into [`0025-simple-udt`](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0025-simple-udt/0025-simple-udt.md).

The question is where to put `anyone_can_pay/cheque` script information?

**Comment by janx** [comment]
Each new lock/script after genesis block worth its own RFC I think.
