### ISSUE TITLE
RFC 23 DAO Deposit Withdraw should mention RFC 36 Remove Header Deps Immature Rule

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/rfcs#338]
[RFC 23 DAO Deposit Withdraw](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw.md) should mention and be updated accordingly to [RFC 36 Remove Header Deps Immature Rule](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0036-remove-header-deps-immature-rule/0036-remove-header-deps-immature-rule.md), but RFC 23 has no reference of RFC 36, not even in the updated editorial review #334.

**Background**: while I was keeping an eye on RFC 23, I wouldn't be aware of RFC 36 if not for @jordanmack [issue in my CKB++ proposal](https://github.com/phroi/CKBpp/issues/1).

Keep up the great work :muscle:
Phroi

**Comment by janx** [comment]
Good catch. Would you like to submit a PR? @phroi
