### ISSUE TITLE
🐞 transaction-parallelism

### ISSUE THREAD

**Issue by u2** [nervosnetwork/rfcs#70]
https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0002-ckb/images/transaction-parallelism.png

In this figure, C2 describes the `Input conflict` scenario, but the figure describes `Inputs / Dependents conflict`, they are not consistent. Moreover, the description should be `Inputs conflict`, it should be plural.

**Comment by doitian** [comment]
I'm sorry but it seems that @github is not going to fix the 500 issue. The team could not open this PR in desktop browser, it is inconvenient to discuss in this issue.  Could you please close this and create a new one instead?
